### ISSUE TITLE
Usable in a real browser?

### ISSUE THREAD

**Issue by rektide** [mantoni/mocaccino.js#10]
I'm still looking for some way to run mocha tests against a real browser, where they can be debugged when they aren't working. Is there any alternative to phantomic that will let me run mocaccino tests against a real browser?

**Comment by rektide** [comment]
Just found https://github.com/mantoni/min-webdriver . Would appreciate it's mention in the docs! Finding options for real-browser testing mocha scripts has been nightmarish.

**Comment by mantoni** [comment]
Both, mocaccino and min-webdriver are part of a more convenient tool called Mochify:
https://github.com/mantoni/mochify.js

It also offers the `--consolify` option which allows you to generate a standalone web page:
https://github.com/mantoni/consolify

Why not make a pull request with the doc changes?

**Comment by mantoni** [comment]
The docs now mention the other projects. Thanks.
