### ISSUE TITLE
Add support to third party reporters

### ISSUE THREAD

**Issue by mkautzmann** [mantoni/mocaccino.js#11]
Hello everyone.

After using [mochify](https://github.com/mantoni/mochify.js) for a while and looking into [this issue](https://github.com/mantoni/mochify.js/issues/87).

I think it would be nice to add support to third party reporters on mocaccino. I've been trying to develop a solution to the problem but I stumbled upon a [mocha's bug](https://github.com/mochajs/mocha/issues/880).

The problem seems to be that browserify are looking for Mocha-related modules in the wrong place, it looks for modules on `./lib-cov/mocha`?!

After some searching I found out that mocha actually relies on a the `COV` environment variable to decide where to require. I think that's really odd.

Tried manually setting `COV` to `false` but it looks like something is overriding it.

I can send the PR with the work in progress for analysis and discussion. The code should be OK already for reporters that don't require Mocha internally (almost none actually :disappointed:).

Any thoughts?

**Comment by mantoni** [comment]
This is actually the reason why this project exists. I'm injecting the browser version of mocha into the bundle stream to make it all work. Therefore I don't really understand why you're running into issues.

Go ahead and make a PR with what you have. We can iterate on that.

**Comment by mkautzmann** [comment]
OK, now that you said that I managed to make it work by adding the reporter to the bundle before it gets transformed by mocaccino. Take a look at the related PR.

**Comment by mantoni** [comment]
This feature has been released in `1.6.0`.
