### ISSUE TITLE
Un-source-mapped stack traces in when used with Chai assertions

### ISSUE THREAD

**Issue by Mr0grog** [mantoni/mocaccino.js#18]
I was just experimenting with Mochify and was having trouble getting stack traces to be properly source-mapped. Specifically, normal exceptions in PhantomJS are source-mapped properly, but exceptions created by Chai assertions (which are instances of [`assertion-error`](https://github.com/chaijs/assertion-error)), do not get properly source-mapped. I think normal assertions in newer browsers would also not get properly source-mapped.

The problem is actually that Mocha tries to clean up the stack trace and make it more presentable. On built-in exceptions in PhantomJS, the `stack` property of an error is not-writable, so the cleaned-up trace is never saved and used. On chai assertion errors (and on errors in the latest Safari and Chrome), that property *is* writable. The cleaned-up stack trace does not get matched by the `source-mapper` instance in Phantomic and therefore isn’t mapped back to the correct source file and line.

I think the easy solution to this is for Mocaccino to expose Mocha’s `full-trace` option and for Mochify to set it to `true`. That prevents Mocha from cleaning up the traces.

Otherwise, maybe this is really an issue for `source-mapper`? It seems like the cleaned up traces could be hard to match reliably without accidentally transforming other lines of text that aren’t part of a stack trace.

For reference, here’s a raw trace:

```
AssertionError@http://localhost:59870/js/bundle:570:24
assert@http://localhost:59870/js/bundle:3071:31
include@http://localhost:59870/js/bundle:3384:16
assert@http://localhost:59870/js/bundle:6986:54
http://localhost:59870/js/bundle:11101:44
callFn@http://localhost:59870/js/bundle:15714:25
run@http://localhost:59870/js/bundle:15707:13
runTest@http://localhost:59870/js/bundle:16178:13
http://localhost:59870/js/bundle:16284:19
next@http://localhost:59870/js/bundle:16098:16
http://localhost:59870/js/bundle:16108:11
next@http://localhost:59870/js/bundle:16040:16
http://localhost:59870/js/bundle:16076:9
timeslice@http://localhost:59870/js/bundle:11318:27
```

…and the same trace after being cleaned up by Mocha, where `source-mapper` fails to identify it:

```
AssertionError@js/bundle:570:24
assert@js/bundle:3071:31
include@js/bundle:3384:16
assert@js/bundle:6986:54
js/bundle:11101:44
callFn@js/bundle:15714:25
run@js/bundle:15707:13
runTest@js/bundle:16178:13
js/bundle:16284:19
next@js/bundle:16098:16
js/bundle:16108:11
next@js/bundle:16040:16
js/bundle:16076:9
timeslice@js/bundle:11318:27
```

**Comment by mantoni** [comment]
Hm, interesting case. I guess making the `source-mapper` regexp more flexible is the cleanest solution. Even if it matches anything that ends with `:123:456` it should be pretty save and not destroy any other output. Maybe it should just try to match as much as possible and default to the original output if the no match was found. Does that sound reasonable?

**Comment by Mr0grog** [comment]
Yeah, changing the `source-mapper` to be more flexible would solve this, too. I’ll close this and file an issue on that repo.
