### ISSUE TITLE
Deprecate phantomjs support?

### ISSUE THREAD

**Issue by albertyw** [mantoni/mocaccino.js#29]
Given that phantomjs seems to have been suspended 2 years ago (https://github.com/ariya/phantomjs/issues/15344) and mindshare has moved to chromium, should this project deprecate phantomjs support? 

Removing phantomjs would also "fix" the current build failure in https://travis-ci.org/github/mantoni/mocaccino.js/jobs/662142311.

**Comment by mantoni** [comment]
This module might get dropped entirely in a furture version of Mochify. I don't think it's worth the effort to migrate to a different test setup. If you feel like it anyway, feel free to send a PR and I'll happily merge.

**Comment by albertyw** [comment]
I think this task is now resolved after a90d13a was landed?
